/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpinionesRouteImport } from './routes/opiniones'
import { Route as MenuDelDiaRouteImport } from './routes/menu-del-dia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CartaRouteImport } from './routes/carta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAvisoLegalRouteImport } from './routes/legal.aviso-legal'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionesRoute = OpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuDelDiaRoute = MenuDelDiaRouteImport.update({
  id: '/menu-del-dia',
  path: '/menu-del-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaRoute = CartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAvisoLegalRoute = LegalAvisoLegalRouteImport.update({
  id: '/legal/aviso-legal',
  path: '/legal/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/menu-del-dia': typeof MenuDelDiaRoute
  '/opiniones': typeof OpinionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/menu-del-dia': typeof MenuDelDiaRoute
  '/opiniones': typeof OpinionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/galeria': typeof GaleriaRoute
  '/menu-del-dia': typeof MenuDelDiaRoute
  '/opiniones': typeof OpinionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carta'
    | '/contacto'
    | '/galeria'
    | '/menu-del-dia'
    | '/opiniones'
    | '/sitemap.xml'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carta'
    | '/contacto'
    | '/galeria'
    | '/menu-del-dia'
    | '/opiniones'
    | '/sitemap.xml'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
  id:
    | '__root__'
    | '/'
    | '/carta'
    | '/contacto'
    | '/galeria'
    | '/menu-del-dia'
    | '/opiniones'
    | '/sitemap.xml'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartaRoute: typeof CartaRoute
  ContactoRoute: typeof ContactoRoute
  GaleriaRoute: typeof GaleriaRoute
  MenuDelDiaRoute: typeof MenuDelDiaRoute
  OpinionesRoute: typeof OpinionesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LegalAvisoLegalRoute: typeof LegalAvisoLegalRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opiniones': {
      id: '/opiniones'
      path: '/opiniones'
      fullPath: '/opiniones'
      preLoaderRoute: typeof OpinionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-del-dia': {
      id: '/menu-del-dia'
      path: '/menu-del-dia'
      fullPath: '/menu-del-dia'
      preLoaderRoute: typeof MenuDelDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta': {
      id: '/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof CartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aviso-legal': {
      id: '/legal/aviso-legal'
      path: '/legal/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof LegalAvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartaRoute: CartaRoute,
  ContactoRoute: ContactoRoute,
  GaleriaRoute: GaleriaRoute,
  MenuDelDiaRoute: MenuDelDiaRoute,
  OpinionesRoute: OpinionesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LegalAvisoLegalRoute: LegalAvisoLegalRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
